const fs = require('fs');
const ptMissing = JSON.parse(fs.readFileSync('missing_keys.json', 'utf8'));

const enTranslations = {
  "hero_subtitle": "Life, health, auto, home, business, and international solutions for the Brazilian community.",
  "services_subtitle": "We offer strategic protection solutions for families, professionals, and businesses in the Brazilian community, with personalized service and a focus on what really matters: your safety and peace of mind.",
  "hero_help": "HOW CAN WE HELP YOU?",
  "form_name": "Your Full Name",
  "footer_desc": "Everything involving insurance for Brazilian families and businesses in the United States, offering clear guidance, personalized solutions, and support at every stage of life.",
  "seo_title_estrategias_patrimoniais": "Dollar Wealth Strategies | Better Life Global Insurance",
  "problem_title": "What problem does this insurance solve?",
  "difference_title": "When does it make a difference?",
  "help_title": "How can Better Life help?",
  "related_title": "Related Solutions",
  "seo_title_protecao_patrimonial": "Asset Protection | Better Life Global Insurance",
  "seo_title_sucessao": "Succession Planning International Life Insurance | Better Life Global Insurance",
  "sucessao_subtitle": "A simple, fast, and efficient way to take care of your family's future.",
  "sucessao_problem": "Transferring assets can be time-consuming, bureaucratic, and generate high costs. International Life Solutions allows beneficiaries to receive funds directly from the insurance company, without relying on the traditional probate process, providing liquidity and speed right when the family needs it most.",
  "sucessao_difference_0": "When you want to facilitate asset succession.",
  "sucessao_difference_1": "When you want to offer immediate liquidity to your family.",
  "sucessao_difference_2": "When you seek to reduce bureaucracy in transferring policy funds.",
  "sucessao_difference_3": "When you want to financially protect future generations.",
  "sucessao_difference_4": "When you intend to organize your succession in advance.",
  "sucessao_difference_5": "When you value efficiency, simplicity, and predictability.",
  "sucessao_help": "We analyze your family structure and succession goals to demonstrate how an international solution can complement your family's estate planning and provide more peace of mind for future generations.",
  "seo_title_vida_internacional": "International Life Solutions | Better Life Global Insurance",
  "seo_title_bop": "Business Owner's Policy (BOP) | Better Life Global Insurance",
  "bop_name": "Business Owner's Policy (BOP)",
  "bop_subtitle": "The main protections for your business in a single policy.",
  "bop_problem": "A fire, a robbery, an accident with a customer, or a business interruption can compromise the company's cash flow. The BOP combines essential protections for small and medium-sized businesses into a simpler solution.",
  "bop_difference_0": "When equipment, furniture, or merchandise are damaged.",
  "bop_difference_1": "When fire, theft, or other covered events occur.",
  "bop_difference_2": "When a customer suffers an accident at the establishment.",
  "bop_difference_3": "When the company is held liable for damages to third parties.",
  "bop_difference_4": "When a covered event temporarily prevents the business from operating.",
  "bop_help": "We understand how the company works, where it operates, what assets it owns, and what risks it faces. From there, we build a protection that matches the reality of the business, avoiding both gaps and unnecessary coverage.",
  "seo_title_carro": "Auto Insurance | Better Life Global Insurance",
  "carro_name": "Auto Insurance",
  "carro_subtitle": "Protection for you, your vehicle, and your assets.",
  "carro_problem": "An accident can cause damage to your car, other vehicles, and even people involved. Auto Insurance reduces this financial impact and helps you get back to your routine more quickly.",
  "carro_difference_0": "When you are involved in an accident.",
  "carro_difference_1": "When you cause damage to someone else's vehicle or property.",
  "carro_difference_2": "When someone gets hurt in an accident involving your car.",
  "carro_difference_3": "When your vehicle is stolen or burglarized.",
  "carro_difference_4": "When heavy rain, hail, falling objects, or other events damage the car.",
  "carro_difference_5": "When you need towing or roadside assistance, depending on the coverage.",
  "carro_help": "We analyze who drives the vehicle, how it is used, where it is parked, and what protection makes sense for your reality. Then, we compare options to balance coverage, deductible, and price — without leaving you unprotected just to get a lower monthly premium.",
  "residencial_name": "Home Insurance",
  "residencial_subtitle": "Your home protected against life's unforeseen events.",
  "vida_name": "Life Insurance",
  "vida_subtitle": "Financial protection for you and those who depend on you.",
  "seo_title_commercial_auto": "Commercial Auto Insurance | Better Life Global Insurance",
  "seo_title_commercial_property": "Commercial Property Insurance | Better Life Global Insurance",
  "seo_title_cyber_liability": "Cyber Liability Insurance | Better Life Global Insurance",
  "seo_title_general_liability": "General Liability for Businesses | Better Life Global Insurance",
  "seo_title_pets": "Pet Insurance | Better Life Global Insurance",
  "pets_name": "Pet Insurance",
  "pets_subtitle": "Protection for those who are also part of the family.",
  "pets_problem": "Consultations, exams, surgeries, and veterinary emergencies can generate high expenses. Pet Insurance helps you take care of your animal's health without having to decide between the necessary treatment and the impact on your budget.",
  "pets_difference_0": "When your pet gets sick.",
  "pets_difference_1": "When they suffer an accident.",
  "pets_difference_2": "When they need exams or medication.",
  "pets_difference_3": "When a surgery becomes necessary.",
  "pets_difference_4": "When a veterinary emergency occurs.",
  "pets_difference_5": "When you want to maintain preventive care, according to the chosen plan.",
  "pets_help": "We evaluate your pet's age, breed, and needs to compare coverage options, deductibles, reimbursements, and limitations. You choose clearly and know how the plan can be used.",
  "seo_title_professional_liability": "Professional Liability (E&O) | Better Life Global Insurance",
  "seo_title_residencial": "Home Insurance | Better Life Global Insurance",
  "residencial_problem": "Your home represents an important part of your family's assets. Home Insurance helps reduce losses when fires, storms, thefts, accidents, or other covered events cause damage to the property or your belongings.",
  "residencial_difference_0": "When a storm causes damage to the roof or structure.",
  "residencial_difference_1": "When a fire hits the residence.",
  "residencial_difference_2": "When a pipe bursts and causes damage covered by the policy.",
  "residencial_difference_3": "When theft or vandalism occurs.",
  "residencial_difference_4": "When furniture, appliances, or other belongings are damaged by a covered event.",
  "residencial_difference_5": "When someone suffers an accident on your property and you may be held liable.",
  "residencial_help": "In Florida, it is not enough to hire just any home insurance. We evaluate the characteristics of the property, the region, the type of construction, and the risks that need to be considered to find adequate protection for your home and assets.",
  "umbrella_name": "Umbrella Insurance",
  "umbrella_subtitle": "Additional protection for the assets you've built.",
  "seo_title_saude": "Health Insurance | Better Life Global Insurance",
  "saude_name": "Health Insurance",
  "saude_subtitle": "Take care of your health without putting your assets at risk.",
  "saude_problem": "Consultations, exams, surgeries, and hospitalizations can be very expensive in the United States. Health Insurance facilitates access to medical care and reduces the risk of an unexpected expense compromising your family's budget.",
  "saude_difference_0": "When you need to see a doctor.",
  "saude_difference_1": "When you need to undergo exams or treatments.",
  "saude_difference_2": "When an emergency happens.",
  "saude_difference_3": "When a surgery or hospitalization becomes necessary.",
  "saude_difference_4": "When your family needs regular medical follow-up.",
  "saude_difference_5": "When you want to take care of your health preventively.",
  "saude_help": "We analyze your family's needs, the doctors you wish to use, your region, your income, and your budget. Thus, we help you understand the options and choose a plan you can actually use.",
  "seo_title_surety_bonds": "Surety Bonds | Better Life Global Insurance",
  "seo_title_umbrella": "Umbrella Insurance | Better Life Global Insurance",
  "umbrella_problem": "Some accidents can result in claims far exceeding the limits of Auto or Home Insurance. Umbrella adds an extra layer of liability to help protect your assets.",
  "umbrella_difference_0": "When a car accident causes serious damage to other people.",
  "umbrella_difference_1": "When someone suffers a serious accident on your property.",
  "umbrella_difference_2": "When the amount of a claim exceeds the primary insurance limit.",
  "umbrella_difference_3": "When there are high legal fees and settlements.",
  "umbrella_difference_4": "When you own a home, investments, income, or other assets you wish to preserve.",
  "umbrella_help": "We analyze your current insurance and the assets that need to be protected. Then, we check if the existing limits are sufficient or if an additional layer of protection makes sense for your life.",
  "seo_title_viagem": "Travel Insurance | Better Life Global Insurance",
  "viagem_name": "Travel Insurance",
  "viagem_subtitle": "Travel knowing you have someone to turn to.",
  "viagem_problem": "A medical emergency, lost luggage, or a trip cancellation can cause expenses and a lot of worry. Travel Insurance provides support to deal with unforeseen events far from home.",
  "viagem_difference_0": "When you need medical care during the trip.",
  "viagem_difference_1": "When you suffer an accident far from home.",
  "viagem_difference_2": "When your luggage is lost or delayed.",
  "viagem_difference_3": "When the trip needs to be canceled or interrupted due to a covered situation.",
  "viagem_difference_4": "When a significant delay occurs.",
  "viagem_difference_5": "When you need guidance or assistance in another country.",
  "viagem_help": "We consider the destination, duration, age of travelers, and type of trip to find a suitable option. This way, you travel with a protection compatible with your plans, without hiring unnecessary coverage.",
  "seo_title_vida": "Life Insurance | Better Life Global Insurance",
  "vida_problem": "If something happens to you, such as a serious illness, accident, or even death, family expenses continue. Life Insurance helps you in the event of a serious illness or helps those you love keep the house, pay bills, take care of children's education, and get through a difficult time with more financial security.",
  "vida_difference_0": "When your family depends on your income.",
  "vida_difference_1": "When you have children, a spouse, or family members under your responsibility.",
  "vida_difference_2": "When there is a mortgage, debts, or other important expenses.",
  "vida_difference_3": "When you want to leave financial protection for those you love.",
  "vida_difference_4": "When you want to prepare for situations such as disability or serious illness, with living benefits.",
  "vida_help": "We understand your reality, your responsibilities, and your goals before recommending any solution. Then, we look for adequate protection for your family and your budget.",
  "seo_title_workers_comp": "Workers' Compensation | Better Life Global Insurance"
};

let mainjs = fs.readFileSync('main.js', 'utf8');

let ptStr = '';
for (const [k, v] of Object.entries(ptMissing)) {
    ptStr += '        ' + k + ': "' + v + '",\n';
}

let enStr = '';
for (const [k, v] of Object.entries(enTranslations)) {
    enStr += '        ' + k + ': "' + v.replace(/"/g, '\\"') + '",\n';
}

mainjs = mainjs.replace(/(pt:\s*{[\s\S]*?)(};|\s*en:)/, (match, p1, p2) => p1 + '\n' + ptStr + '\n' + p2);
mainjs = mainjs.replace(/(en:\s*{[\s\S]*?)(};)/, (match, p1, p2) => p1 + '\n' + enStr + '\n' + p2);

fs.writeFileSync('main.js', mainjs, 'utf8');
console.log('Successfully injected missing translations into main.js');
